print("Hello")
print("Information and Network Engineering")
print("Hello Pakin you will be great")

print("I'm hungry")
print('He ask me "Who got the book?"')

print("I'm good and \"I will do my best\"")
print("/\\")

print("Hi")
print("My name is Pakin")
print("I am 19 years old")
print("I Study in Faculty of Information and Network Engineering")
print("My branch is INET")

print("I always exercise every day.")
print("I always eat healthy food.")
print("I always sleep early.")
print("I always play games with my friends.")
print("We play OW.")
print("OW is a fun game.")
print("But always have many bad team.")
print("I like another game too.")
print("I like to play Roblox.")
print("I play Roblox like AFK map.")
print("I like play Roblox easily map.")
print("Because I always AFK.")